import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

export async function GET() {
  const now = new Date();
  return NextResponse.json({
    data: [
      {
        id: "openai",
        name: "OpenAI GPT-4o",
        baseUrl: "https://api.openai.com/v1",
        apiKeyMasked: "sk-****7f3a",
        chatModel: "gpt-4o",
        embeddingModel: "text-embedding-3-large",
        enabled: true,
        defaultStrategy: "balanced",
        systemPrompt: "你是一个轮毂表面缺陷检测领域的专业AI助手，擅长分析检测数据、识别缺陷模式并提供质量改进建议。",
        createdAt: "2025-02-10T10:00:00Z",
        updatedAt: now.toISOString(),
        lastVerifiedAt: now.toISOString(),
      },
      {
        id: "deepseek",
        name: "DeepSeek 深度求索",
        baseUrl: "https://api.deepseek.com/v1",
        apiKeyMasked: "sk-****2b8e",
        chatModel: "deepseek-chat",
        embeddingModel: "deepseek-embedding",
        enabled: true,
        defaultStrategy: "precision",
        systemPrompt: "你是轮毂检测产线的智能分析助手，请基于工业检测数据提供精准的缺陷分类和质量评估。",
        createdAt: "2025-04-18T14:30:00Z",
        updatedAt: now.toISOString(),
        lastVerifiedAt: new Date(now.getTime() - 1800000).toISOString(),
      },
      {
        id: "qwen",
        name: "通义千问 Qwen-Max",
        baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
        apiKeyMasked: "sk-****9c1d",
        chatModel: "qwen-max",
        embeddingModel: "text-embedding-v3",
        enabled: true,
        defaultStrategy: "creative",
        systemPrompt: "你是轮毂制造质量管控专家，能够综合分析产线数据、检测图像和工艺参数，提供全面的质量诊断和工艺优化建议。",
        createdAt: "2025-05-22T09:15:00Z",
        updatedAt: now.toISOString(),
        lastVerifiedAt: new Date(now.getTime() - 600000).toISOString(),
      },
      {
        id: "zhipu",
        name: "智谱 GLM-4",
        baseUrl: "https://open.bigmodel.cn/api/paas/v4",
        apiKeyMasked: "****a5f2",
        chatModel: "glm-4-plus",
        embeddingModel: "embedding-3",
        enabled: true,
        defaultStrategy: "balanced",
        systemPrompt: "你是工业视觉检测领域的AI分析助手，专注于轮毂表面缺陷的智能识别、根因分析和预防措施建议。",
        createdAt: "2025-06-01T16:00:00Z",
        updatedAt: now.toISOString(),
        lastVerifiedAt: new Date(now.getTime() - 900000).toISOString(),
      },
      {
        id: "local-qwen",
        name: "本地推理服务 Qwen2.5-72B",
        baseUrl: "http://192.168.10.200:8000/v1",
        apiKeyMasked: "local-****",
        chatModel: "qwen2.5-72b-instruct",
        embeddingModel: "bge-m3",
        enabled: true,
        defaultStrategy: "precision",
        systemPrompt: "你是部署在本地内网的轮毂检测AI助手，所有数据处理均在本地完成，确保数据安全。擅长缺陷模式识别和产线异常预警。",
        createdAt: "2025-07-08T11:00:00Z",
        updatedAt: now.toISOString(),
        lastVerifiedAt: new Date(now.getTime() - 300000).toISOString(),
      },
      {
        id: "local-yi",
        name: "本地推理服务 Yi-1.5-34B",
        baseUrl: "http://192.168.10.201:8000/v1",
        apiKeyMasked: "local-****",
        chatModel: "yi-1.5-34b-chat",
        embeddingModel: "bge-large-zh",
        enabled: false,
        defaultStrategy: "balanced",
        systemPrompt: "你是轮毂质量检测辅助分析系统，提供缺陷分类和统计报表分析功能。",
        createdAt: "2025-08-15T08:30:00Z",
        updatedAt: new Date(now.getTime() - 86400000).toISOString(),
        lastVerifiedAt: new Date(now.getTime() - 172800000).toISOString(),
      },
    ],
  });
}
